# This file was generated by GoReleaser. DO NOT EDIT.
cask "prem-down" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8c4ab3743c304201c5baae51d4542120034809bf9aa3cc673cf469cced023760"
      url "https://github.com/lucuma13/prem-down/releases/download/#{version}/prem-down_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcc8105dff5bb37181ab4df4074b2825fc185554f5752330007abdf744f75fcb"
      url "https://github.com/lucuma13/prem-down/releases/download/#{version}/prem-down_darwin_arm64.tar.gz"
    end
  end

  name "prem-down"
  desc "Downgrade Premiere Pro project files so older versions can open them"
  homepage "https://github.com/lucuma13/prem-down"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prem-down"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/prem-down")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prem-down"]
    end
  end

  # No zap stanza required

end
