# This file was generated by GoReleaser. DO NOT EDIT.
cask "prem-down" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "147062ea8d3171737abde8d2df4480665fa746bb7c5d40b3269e3a9a69d1e97c"
      url "https://github.com/lucuma13/prem-down/releases/download/#{version}/prem-down_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee55c76384bafd428dae52df1b106a7f777e3db4d3e72a2c936bc54f3d6b3559"
      url "https://github.com/lucuma13/prem-down/releases/download/#{version}/prem-down_darwin_arm64.tar.gz"
    end
  end

  name "prem-down"
  desc "Downgrade Premiere Pro project files so older versions can open them"
  homepage "https://github.com/lucuma13/prem-down"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prem-down"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/prem-down")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prem-down"]
      system_command "#{staged_path}/prem-down", args: ["integrate"]
    end
  end

  uninstall_preflight do
    if OS.mac? && File.exist?("#{staged_path}/prem-down")
      system_command "#{staged_path}/prem-down", args: ["integrate", "--remove"], must_succeed: false
    end
  end

  # No zap stanza required

end
