# This file was generated by GoReleaser. DO NOT EDIT.
cask "prem-down" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "71b6698d6ee062562374e460bd03774e5d1cecb959f990bc0451539f4a07466e"
      url "https://github.com/lucuma13/prem-down/releases/download/#{version}/prem-down_binary_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "db70fceb0e6d617e321461f6c72711251194c8d24b1cf2ef37624373d6b4eced"
      url "https://github.com/lucuma13/prem-down/releases/download/#{version}/prem-down_binary_macos_arm64.tar.gz"
    end
  end

  name "prem-down"
  desc "Downgrade Premiere Pro project files so older versions can open them"
  homepage "https://github.com/lucuma13/prem-down"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prem-down"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/prem-down")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prem-down"]
      system_command "#{staged_path}/prem-down", args: ["integrate"]
    end
  end

  uninstall_preflight do
    if OS.mac? && File.exist?("#{staged_path}/prem-down")
      system_command "#{staged_path}/prem-down", args: ["integrate", "--remove"], must_succeed: false
    end
  end

  # No zap stanza required

end
