name: Check for ASC-MHL Updates
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-ascmhl:
    runs-on: ubuntu-latest
    steps:
      - name: Check PyPI for ascmhl
        id: check
        run: |
          LATEST=$(curl -s https://pypi.org/pypi/ascmhl/json | jq -r .info.version)
          echo "latest_version=$LATEST" >> $GITHUB_OUTPUT
      
      - name: Open Issue on mhlver Repo
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/lucuma13/mhlver/issues
          title: "Dependency Update: ascmhl ${{ steps.check.outputs.latest_version }}"
          body: "A new version of ascmhl is available on PyPI. Update the resources in the Homebrew Tap."
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_BUMP_TOKEN }}